function(melt_doxygen _target)
  option(MELT_ENABLE_DOXYGEN "Enable doxygen doc builds of source" OFF)
  if(MELT_ENABLE_DOXYGEN)
    set(DOXYGEN_CALLER_GRAPH ON)
    set(DOXYGEN_CALL_GRAPH ON)
    set(DOXYGEN_EXTRACT_ALL ON)
    find_package(Doxygen REQUIRED dot)
    doxygen_add_docs(${_target}-docs ${${_target}_SOURCE_DIR})

  endif()
endfunction()
